// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLZBfae9na4pe-zDAUs-9BRiHz-_LRN3w',
    appId: '1:1072506645441:web:32c93fbb4800f7f53c5d40',
    messagingSenderId: '1072506645441',
    projectId: 'hearyou-6f443',
    authDomain: 'hearyou-6f443.firebaseapp.com',
    storageBucket: 'hearyou-6f443.firebasestorage.app',
    measurementId: 'G-ZHZLSE1XXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKOIx9L0jGUNFw0gOxS7cT4_WvxhgkVd0',
    appId: '1:1072506645441:android:db8ea52bc51505423c5d40',
    messagingSenderId: '1072506645441',
    projectId: 'hearyou-6f443',
    storageBucket: 'hearyou-6f443.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtmyH3Ao1xrgWetYFFLb0VQqxTTghqZDE',
    appId: '1:1072506645441:ios:fb176079155e92c93c5d40',
    messagingSenderId: '1072506645441',
    projectId: 'hearyou-6f443',
    storageBucket: 'hearyou-6f443.firebasestorage.app',
    iosBundleId: 'com.example.seniorapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtmyH3Ao1xrgWetYFFLb0VQqxTTghqZDE',
    appId: '1:1072506645441:ios:fb176079155e92c93c5d40',
    messagingSenderId: '1072506645441',
    projectId: 'hearyou-6f443',
    storageBucket: 'hearyou-6f443.firebasestorage.app',
    iosBundleId: 'com.example.seniorapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLZBfae9na4pe-zDAUs-9BRiHz-_LRN3w',
    appId: '1:1072506645441:web:f611f078b29e8bf43c5d40',
    messagingSenderId: '1072506645441',
    projectId: 'hearyou-6f443',
    authDomain: 'hearyou-6f443.firebaseapp.com',
    storageBucket: 'hearyou-6f443.firebasestorage.app',
    measurementId: 'G-ZW66Q936LF',
  );
}
